baseURL = "/"
languageCode = 'en-us'
title = 'The Big Data Space'
theme = "spectral"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true	

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/about/'
title = "About"

[[params.menu.main]]
url = '/contact/'
title = "Contact"

[[params.menu.main]]
url = 'https://iceberg.thebigdata.space'
title = "Iceberg"

[[params.menu.main]]
url = 'https://deltalake.thebigdata.space/'
title = "DeltaLake"


[params]
fancyTitle = "The Big Data Space" # title for frontpage, may include image
description = 'Success in Big Data'
body_is_markdown = true

[params.one]
enable = true
title = 'Big Data made easy'
body = 'This site is dedicated to exploring the Big Data space'
body_is_markdown = true


[params.two]
enable = true

[[params.two.section]]
img = "img/deep_space.webp"
img_alt = "Deep Space"
body = '''
We look at Big Data architecture and technologies.
'''
body_is_markdown = true

[params.three]
enable = true
title = 'Experience Counts'
body = '''
A playground for all things related to Big Data
'''

[[params.three.feature]]
icon = "solid fa-code"
title = "Better Design"
body = "We use Behaviour Driven Design tests to demonstrate the best designs."
